#!/usr/bin/perl -w
use Data::Dumper;
my $mac; 
my $ip;
my $hostname;
($mac,$ip,$hostname)=@ARGV;

sub usage{
    print "Usage: dhcpop <mac address> [<ip address>] [<host name>]\n";
}

if(!defined $mac or $mac eq "-h" ){
    &usage;
    exit 1;
}

my $out=qx(tabdump -w key==omapi -w username==xcat_key  passwd |tail -n1|awk -F, '{print \$2","\$3}');

$out =~ s/("|\n)//g;
my ($id,$passwd)=split(',',$out);

if(-z "$id" || -z "$passwd" ){
    print "Error: no 'omapi' entry defined in passwd table!";
    exit 1;
}

my $omshell;
open($omshell, "|/usr/bin/omshell >/dev/null");
print $omshell "key "
  . $id . " \""
  . $passwd . "\"\n";
print $omshell "connect\n";

if($hostname){
    print $omshell "new host\n";
    print $omshell
      "set name = \"$hostname\"\n";    #Find and destroy conflict name
    print $omshell "open\n";
    print $omshell "remove\n";
    print $omshell "close\n";
}

if ($mac)
{
    print $omshell "new host\n";
    print $omshell "set hardware-address = " . $mac
      . "\n";                      #find and destroy mac conflict
    print $omshell "open\n";
    print $omshell "remove\n";
    print $omshell "close\n";
}

if($ip){
   print $omshell "new host\n";
   print $omshell
    "set ip-address = $ip\n";    #find and destroy ip conflict
   print $omshell "open\n";
   print $omshell "remove\n";
   print $omshell "close\n";
}


close($omshell);
#print "$mac-$ip-$hostname\n"

